apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blockcertify-role
  labels:
    app: blockcertify

rules:
  # Read-only access to required resources
  - apiGroups: [ "" ]
    resources: [ "configmaps", "secrets" ]
    verbs: [ "get", "list", "watch" ]