apiVersion: apps/v1
kind: Deployment
metadata:
  name: diyet-app
spec:
  template:
    spec:
      containers:
        - name: diyet-app
          env:
            - name: SERVER_PORT
              value: "5076"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"
            # Redis
            - name: REDIS_HOST
              value: "redis.data.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            # PostgreSQL
            - name: DB_HOST
              value: "postgres-rw.data.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: diyet-app-secrets
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: diyet-app-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: diyet-app-secrets
                  key: db-password
            # Kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
