# ============================
# Kustomization - Base
# Diyet App - Base Configuration
# ============================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: diyet-app-base

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app: diyet-app
      version: v1


commonAnnotations:
  managed-by: flux