# ============================
# ServiceAccount
# Diyet App - Service Account for RBAC
# ============================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: diyet-app
  labels:
    app: diyet-app
imagePullSecrets:
  - name: docker-registry-secret